const data = [
    {
        name: "Elira Pendora",
        JPname: "エリーラ ペンドラ",
        bio: "A sky dragon who came from the heavens closest to the sun. She has the kindness and receptiveness that makes the light of a sunny day fall equally on all.",
        JPbio: "太陽に最も近い天空からやって来た天空竜。彼女は、晴れた日の光を誰にでも平等に当てる優しさと包容力を持っています。",
        gender: "Female",
        age: "Never ask a lady her age",
        birthday: "October 16",
        height: "160 cm/5 foot 2 inches",
        color: "#95C8D8",
        fanName: "FamElira",
        image: "/src/assets/niji_pics/lazulight/background remove fullbody.png",
        videoUrl: "https://www.youtube.com/embed/nQb5s3QXFGA?si=6wfZNSsDxDEORhVW",
        twitter: "https://x.com/EliraPendora",
        youtube: "https://www.youtube.com/channel/UCIeSUTOTkF9Hs7q3SGcO-Ow",
        twitch: "https://www.twitch.tv/elirapendora",
        gallery: [
            "/src/assets/niji_pics/lazulight/background%20remove%20elira%20portrait.png",
            "/src/assets/niji_pics/lazulight/background%20remove%20fullbody.png",
            "/src/assets/niji_pics/lazulight/background%20remove.png",
            "/src/assets/niji_pics/lazulight/Elira_Pandora_-_Key_Visual.webp",
            "/src/assets/niji_pics/lazulight/Elira_Pendora_-_April_2023_Costume.webp",
            "/src/assets/niji_pics/lazulight/Elira_Pendora_-_January_2022_Costume.webp",
            "/src/assets/niji_pics/lazulight/Elira_Pendora_-_October_2023_outfit.webp",
            "/src/assets/niji_pics/lazulight/Eliref1.webp",
            "/src/assets/niji_pics/lazulight/Eliref2.webp"
        ]
    },
    {
        name: "Finana Ryugu",
        JPname: "フィナーナ 竜宮",
        bio: "A mermaid who spends her time with tropical fish in the sea of coral reefs. Has a heart as clear and pure as the calm and beautiful sea.",
        JPbio: "サンゴ礁の海で熱帯魚たちと過ごす人魚。穏やかで美しい海のように透き通った純粋な心を持っています。",
        gender: "Female",
        age: "FROOTLOOP",
        birthday: "June 21",
        height: "140 cm/4 foot 7 inches",
        color: "#79CFB8",
        fanName: "Ryuguards",
        image: "/src/assets/niji_pics/lazulight/finana full body background remove.png",
        videoUrl: "https://www.youtube.com/embed/3JAXcwDydNI?si=jlzBwjrFJl2cOMxU",
        twitter: "https://twitter.com/FinanaRyugu",
        youtube: "https://www.youtube.com/@FinanaRyugu",
        twitch: "https://www.twitch.tv/finanaryugu",
        gallery: [
            "/src/assets/niji_pics/lazulight/Finana_Ryugu_Portrait.webp",
            "/src/assets/niji_pics/lazulight/finana%20full%20body%20background%20remove.png",
            "/src/assets/niji_pics/lazulight/background%20remove%20finana.png",
            "/src/assets/niji_pics/lazulight/Finana_Ryugu_-_Key_Visual.webp",
            "/src/assets/niji_pics/lazulight/Finana_Ryugu_-_January_2022_Costume.webp",
            "/src/assets/niji_pics/lazulight/Finana_Ryugu_-_February_2023_Outfit.webp",
            "/src/assets/niji_pics/lazulight/FinaRef1.webp",
            "/src/assets/niji_pics/lazulight/FinaRef2.webp"
        ]
    },
    {
        name: "Petra Gurin",
        JPname: "ペトラ グリン",
        bio: "A penguin who spent much time alone in the frosty sea. Has charm and complex emotions as the stormy sea.",
        JPbio: "凍てつく海で一人で過ごす時間が多かったペンギン。嵐の海のような魅力と複雑な感情を持つ。",
        gender: "Female",
        age: "No ^_^",
        birthday: "December 4",
        height: "152 cm/4 foot 11 inches",
        color: "#FFAE42",
        fanName: "PenTomo",
        image: "/src/assets/niji_pics/obsydia/petra full body background remove.png",
        videoUrl: "https://www.youtube.com/embed/o1M8YeJzdVg?si=xpwvKhD-HQu4OBz9",
        twitter: "https://www.twitter.com/Petra_Gurin/",
        youtube: "https://www.youtube.com/@petragurin",
        twitch: "https://www.twitch.tv/petragurin/",
        gallery: [
            "/src/assets/niji_pics/obsydia/Petra_Gurin_Portrait.webp",
            "/src/assets/niji_pics/obsydia/petra full body background remove.png",
            "/src/assets/niji_pics/obsydia/background remove petra.png",
            "/src/assets/niji_pics/obsydia/petra%20full%20body%20background%20remove2.png",
            "/src/assets/niji_pics/obsydia/petra%20full%20body%20background%20remove3.png",
            "/src/assets/niji_pics/obsydia/Petra_Gurin_August_2022_Outfit_2.webp",
            "/src/assets/niji_pics/obsydia/petra-reference-sheet.jpg",
            "/src/assets/niji_pics/obsydia/petra-reference-sheet2.jpg"
        ]
    },
    {
        name: "Rosemi Lovelock",
        JPname: "ロゼミ ラブロック",
        bio: "A rose maiden raised in a beautiful garden. Pretty as a rose in a vase, but a little sharp to the touch.",
        JPbio: "美しい庭園で育った薔薇の乙女。花瓶に生けたバラのように美しいですが、触ると少し鋭いです。",
        gender: "Female",
        age: "??? years old",
        birthday: "September 16",
        height: "150 cm/4 foot 11 inches",
        color: "#DC3753",
        fanName: "Rosebuds",
        image: "/src/assets/niji_pics/obsydia/rosemi full body background remove.png",
        videoUrl: "https://www.youtube.com/embed/7GJMOUyrHzs?si=4VyjH31vinikt0NM",
        twitter: "https://twitter.com/Rosemi_Lovelock",
        youtube: "https://www.youtube.com/@Rosemi_Lovelock",
        twitch: "https://www.twitch.tv/rosemilovelock",
        gallery: [
            "/src/assets/niji_pics/obsydia/Rosemi_Lovelock_Portrait.webp",
            "/src/assets/niji_pics/obsydia/rosemi full body background remove.png",
            "/src/assets/niji_pics/obsydia/background remove rosemi.png",
            "/src/assets/niji_pics/obsydia/rosemi full body background remove3.png",
            "/src/assets/niji_pics/obsydia/rosemi full body background remove2.png",
            "/src/assets/niji_pics/obsydia/Rosemi_Lovelock_August_2023_Outfit.webp",
            "/src/assets/niji_pics/obsydia/Rosemi_Lovelock_-_Key_Visual.webp",
            "/src/assets/niji_pics/obsydia/Rosemi_Lovelock_-_August_2022_outfit_29.webp",
            "/src/assets/niji_pics/obsydia/rosemi-reference-sheet.jpg"
        ]
    },
    {
        name: "Enna Alouette",
        JPname: "エナー・アールウェット",
        bio: "A blue bird fluttering in the heavens. She sings a love song for the souls of the living.",
        JPbio: "天に羽ばたく青い鳥。彼女は生者の魂のためにラブソングを歌います。",
        gender: "Female",
        age: "??? (blotted out)",
        birthday: "February 20",
        height: "under 150 cm/4 foot 11 inches",
        color: "#858ED1",
        fanName: "Aloupeeps",
        image: "/src/assets/niji_pics/ethyria/enna/enna full body background remove.png",
        videoUrl: "https://www.youtube.com/embed/Xfj3erGrHXU?si=tJojes8gehEOhynM",
        twitter: "https://twitter.com/EnnaAlouette",
        youtube: "https://www.youtube.com/@EnnaAlouette",
        twitch: "https://www.twitch.tv/ennaalouette",
        gallery: [
            "/src/assets/niji_pics/ethyria/enna/Enna_Alouette_Portrait.webp",
            "/src/assets/niji_pics/ethyria/enna/enna full body background remove.png",
            "/src/assets/niji_pics/ethyria/enna/background remove enna.png",
            "/src/assets/niji_pics/ethyria/enna/Enna_Alouette_-_Key_Visual.webp",
            "/src/assets/niji_pics/ethyria/enna/enna full body background remove2.png",
            "/src/assets/niji_pics/ethyria/enna/enna full body background remove3.png",
            "/src/assets/niji_pics/ethyria/enna/Enna_Alouette_Ref_Sheet_New_1.webp",
            "/src/assets/niji_pics/ethyria/enna/Enna_Alouette_Ref_Sheet_New_2.webp",
            "/src/assets/niji_pics/ethyria/enna/Enna_Alouette_Reference_Sheet.webp"
        ]
    },
    {
        name: "Millie Parfait",
        JPname: "ミリー・パフェ",
        bio: "A monster cat creeping through hell. A bit aggressive, but maybe she just needs some attention.",
        JPbio: "地獄を這う化け猫。少し攻撃的ですが、おそらく彼女は少し注意が必要です。",
        gender: "Female",
        age: "500+++",
        birthday: "December 12",
        height: "150 cm/4 foot 11 inches",
        color: "#FEBC87",
        fanName: "FaMillie",
        image: "/src/assets/niji_pics/ethyria/millie/millie full body background remove.png",
        videoUrl: "https://www.youtube.com/embed/mNx_uGgu2rY?si=BaZ6nyxi7eE0Av2P",
        twitter: "twitter.com/MillieParfait",
        youtube: "https://www.youtube.com/@MillieParfait",
        twitch: "https://www.twitch.tv/millieparfait",
        gallery: [
            "/src/assets/niji_pics/ethyria/millie/Millie_Parfait_Portrait.webp",
            "/src/assets/niji_pics/ethyria/millie/millie full body background remove.png",
            "/src/assets/niji_pics/ethyria/millie/background remove millie.png",
            "/src/assets/niji_pics/ethyria/millie/Millie_Parfait_-_Key_Visual.webp",
            "/src/assets/niji_pics/ethyria/millie/Millie_Parfait_Zutto%253Fo_Winter_by_Nanna_Fujimi.webp",
            "/src/assets/niji_pics/ethyria/millie/Multiverse_Merchant_Outfit.webp",
            "/src/assets/niji_pics/ethyria/millie/Millie_Parfait_Reference_Sheet.webp",
            "/src/assets/niji_pics/ethyria/millie/Millie_Zuttomo_Outfit_Reference_Sheet.webp",
            "/src/assets/niji_pics/ethyria/millie/Millie_Multiverse_Merchant_Reference_Sheet.webp"
        ]
    },
    {
        name: "Reimu Endou",
        JPname: "遠藤霊夢",
        bio: "A ghost wandering in hell. The more she thinks of her beloved, the more she becomes sad and haunted.",
        JPbio: "地獄をさまよう幽霊。愛する人のことを考えれば考えるほど、彼女は悲しくなり、取り憑かれてしまいます。",
        gender: "Female",
        age: "???",
        birthday: "November 2",
        height: "155 cm/5 foot 5 inches",
        color: "#B90B4A",
        fanName: "Phantomos",
        image: "/src/assets/niji_pics/ethyria/reimu/reimu full body background remove.png",
        videoUrl: "https://www.youtube.com/embed/74E0i-EZ_s0?si=fR8q-5kfgR0nf2fz",
        twitter: "https://twitter.com/ReimuEndou",
        youtube: "https://www.youtube.com/@ReimuEndou",
        twitch: "https://www.twitch.tv/reimuendou",
        gallery: [
            "/src/assets/niji_pics/ethyria/reimu/Reimu_Endou_Portrait.webp",
            "/src/assets/niji_pics/ethyria/reimu/reimu full body background remove.png",
            "/src/assets/niji_pics/ethyria/reimu/background remove reimu.png",
            "/src/assets/niji_pics/ethyria/reimu/Reimu_Endou_Queen_of_Hearts_Outfit.webp",
            "/src/assets/niji_pics/ethyria/reimu/Reimu_Endou_Reference_Sheet.webp",
            "/src/assets/niji_pics/ethyria/reimu/Reimu_Endou_Queen_of_Heart_Outfit_Reference_Sheet.webp",
            "/src/assets/niji_pics/ethyria/reimu/Reimu_Endou_Lace_Nightwear_Ghost_Reference_Sheet.webp",
            "/src/assets/niji_pics/ethyria/reimu/Reimu_Endou_zutto%253Fo_Summer_Ghost_Outfit_Reference_Sheet.webp"
        ]
    },
    {
        name: "Ike Eveland",
        JPname: "アイク・イーヴランド",
        bio: "A Novelist from the past who seems somewhat closed-off. When an idea for his next work sparks, he becomes a completely different person.",
        JPbio: "どこか閉鎖的な雰囲気を持つ昔ながらの小説家。次回作のアイデアがひらめくと、彼はまったく別人になる。",
        gender: "Male",
        age: "Converting was too hard",
        birthday: "June 12",
        height: "173 cm/5 foot 8 inches",
        color: "#348EC7",
        fanName: "Quilldren",
        image: "/src/assets/niji_pics/luxiem/ike/ike full body background remove.png",
        videoUrl: "https://www.youtube.com/embed/EEiJdPflxR4?si=XdoAOW8SKDKe9xA9",
        twitter: "twitter.com/ike_eveland",
        youtube: "https://www.youtube.com/@IkeEveland",
        twitch: "https://www.twitch.tv/nijisanji_en",
        gallery: [
            ""
        ]
    },
    {
        name: "Luca Kaneshiro",
        JPname: "ルカ・カネシロ",
        bio: "A Mafia boss from the past with a slight temper. Always down for a fight, whether it’s to show-off his own strength or to protect the weak.",
        JPbio: "少し短気な昔のマフィアのボス。 自分の力を誇示するためでも、弱い者を守るためでも、常に戦いを挑んでいます。",
        gender: "Male",
        age: "26",
        birthday: "April 10",
        height: "178 cm/5 foot 10 inches",
        color: "#D4AF37",
        fanName: "Lucubs",
        image: "/src/assets/niji_pics/ethyria/reimu/reimu full body background remove.png",
        videoUrl: "https://www.youtube.com/embed/zniC34tfjrU?si=rs112aZqP5ul1_Sz",
        twitter: "twitter.com/luca_kaneshiro",
        youtube: "https://www.youtube.com/@LucaKaneshiro",
        twitch: "https://www.twitch.tv/nijisanji_en",
        gallery: [
            ""
        ]
    },
    {
        name: "Shu Yamino",
        JPname: "闇ノシュウ",
        bio: "A sorcerer from the past with mysterious abilities. Though kind-hearted, he can call down a malediction upon those who wrong him.",
        JPbio: "過去からやってきた不思議な力を持つ呪術師穏やかな性格の持ち主だが、自分に危害を加えようとする者には容赦なく呪いをかけてしまう",
        gender: "Male",
        age: "uhhhhhhhhhh",
        birthday: "May 2",
        height: "173 cm/5 foot 8 inches",
        color: "#A660A7",
        fanName: "Yaminions",
        image: "/src/assets/niji_pics/luxiem/shu/shu full body background remove.png",
        videoUrl: "https://www.youtube.com/embed/Lmdz1C1rzXM?si=N0H1lPG7HPtDUkMm",
        twitter: "twitter.com/shu_yamino",
        youtube: "https://www.youtube.com/@ShuYamino",
        twitch: "https://www.twitch.tv/nijisanji_en",
        gallery: [
            ""
        ]
    },
    {
        name: "Vox Akuma",
        JPname: "ヴォックス・アクマ",
        bio: "A Demon from the past who held great power Though confident in his superhuman abilities, he looks after those who are loyal to him.",
        JPbio: "過去からやってきた最強の鬼人間離れした身体能力に絶対的な自信を持っているが、仲間や部下のことを常に気にかけている",
        gender: "Male",
        age: "460-500 years old",
        birthday: "April 25",
        height: "178 cm/5 foot 10 inches",
        color: "#960018",
        fanName: "Kindred",
        image: "/src/assets/niji_pics/luxiem/vox/vox full body background remove.png",
        videoUrl: "https://www.youtube.com/embed/nqMp1vooavM?si=_2rfRX6dqAii1650",
        twitter: "twitter.com/Vox_Akuma",
        youtube: "https://www.youtube.com/@VoxAkuma",
        twitch: "https://www.twitch.tv/nijisanji_en",
        gallery: [
            ""
        ]
    },
    {
        name: "Alban Knox",
        JPname: "アルバーン・ノックス",
        bio: "A Phantom Thief from the future with exceptional stealth. He's a free yet mischievous spirit who is hard to pin down.",
        JPbio: "抜群のステルス力を持つ未来から来た怪盗。自由でありながらいたずら好きな性格で、捉えどころがありません。",
        gender: "Male",
        age: "Time travel amnesia...",
        birthday: "May 26",
        height: "175 cm/5 foot 8 inches",
        color: "#FF5F00",
        fanName: "Takaradachi",
        image: "/src/assets/niji_pics/noctyx/alban/alban full body background remove.png",
        videoUrl: "https://www.youtube.com/embed/SFIoMzCIcaE?si=hSD6LzV3cRMEZwuo",
        twitter: "twitter.com/alban_knox",
        youtube: "https://www.youtube.com/@AlbanKnox",
        twitch: "twitch.tv/albanknox",
        gallery: [
            ""
        ]
    },
    {
        name: "Fulgur Ovid",
        JPname: "ファルガー・オーヴィド",
        bio: "A Cyborg from the future with unparalleled strength. His body is partly cold steel, and who's to say if he has a heart?",
        JPbio: "比類のない強さを持った未来から来たサイボーグ。彼の体の一部は冷たい鋼であり、彼に心臓があるかどうかは誰にもわかりません。",
        gender: "Male",
        age: "32",
        birthday: "March 26",
        height: "178 cm/5 foot 10 inches",
        color: "#FF0000",
        fanName: "Comfydants",
        image: "/src/assets/niji_pics/noctyx/fulgur/fulgur full body background remove.png",
        videoUrl: "https://www.youtube.com/embed/WJI7t6MFWUI?si=U2nDLtBlW38fj06B",
        twitter: "twitter.com/Fulgur_Ovid",
        youtube: "https://www.youtube.com/@FulgurOvid",
        twitch: "https://www.twitch.tv/nijisanji_en",
        gallery: [
            ""
        ]
    },
    {
        name: "Sonny Brisko",
        JPname: "サニー・ブリスコー",
        bio: "An Officer from the future with a straightforward attitude. He's reliable in a pinch despite being rough around the edges.",
        JPbio: "まっすぐな態度を持つ未来の将校。荒っぽいけどいざという時には頼りになる。",
        gender: "Male",
        age: "[CLASSIFIED]",
        birthday: "April 6",
        height: "180 cm/5 foot 10 inches",
        color: "#FFF321",
        fanName: "Briskadets",
        image: "/src/assets/niji_pics/noctyx/sonny/sonny full body background remove.png",
        videoUrl: "https://www.youtube.com/embed/Tt6RAjao8xs?si=KsrT6R6nqbBi8ODG",
        twitter: "twitter.com/sonny_brisko",
        youtube: "https://www.youtube.com/@SonnyBrisko",
        twitch: "https://www.twitch.tv/nijisanji_en",
        gallery: [
            ""
        ]
    },
    {
        name: "Uki Violeta",
        JPname: "浮奇ヴィオレタ",
        bio: "A sorcerer from the past with mysterious abilities. Though kind-hearted, he can call down a malediction upon those who wrong him.",
        JPbio: "過去からやってきた不思議な力を持つ呪術師穏やかな性格の持ち主だが、自分に危害を加えようとする者には容赦なく呪いをかけてしまう",
        gender: "Male",
        age: "Doesn't matter anymore",
        birthday: "July 17",
        height: "169 cm/5 foot 6 inches",
        color: "#B600FF",
        fanName: "Stargazers",
        image: "/src/assets/niji_pics/noctyx/uki/uki fuull body background remove.png",
        videoUrl: "https://www.youtube.com/embed/2X39X6ln3BE?si=87_h3_fiOVpFcj-R",
        twitter: "twitter.com/uki_violeta",
        youtube: "https://www.youtube.com/@UkiVioleta",
        twitch: "https://www.twitch.tv/nijisanji_en",
        gallery: [
            ""
        ]
    },
]

export default { data }